apiVersion: apps/v1
kind: Deployment
metadata:
  name: secsample
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: secsample
  template:
    metadata:
      labels:
        app: secsample
    spec:
      containers:
      - name: secsample
        image: pdtacr.azurecr.io/simplcdotnet31:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr-auth


---
apiVersion: v1
kind: Service
metadata:
  name: secsample
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: secsample